### ISSUE TITLE
Games won't load

### ISSUE THREAD

**Issue by kaizen81** [reicast/reicast-emulator#614]
Hello, I'm new to reicast and I' m having trouble loading games . I have put the bios files in the internal storage as instructed (/dc/data). The bios has loaded normally and i got to set the time. I stored the games in the external microsd, but when i choose a game the emulator crashes and returns to desktop . I tried moving the games to the internal storage but i got the same results. Can anyone help please?
I'm using the Nvidia Shiled tablet (Lollipop 5.0.1) and the r6 [382f2e5] reicast version.. Thanks!

**Comment by hooby3dfx** [comment]
How about the play store version?

**Comment by LoungeKatt** [comment]
You may also want to verify the path. Sometimes if you select the path through the GUI, it grabs the version that is the link, but not the true path. It should be /storage/sdcard1 on a Shield tablet.

**Comment by kaizen81** [comment]
The paths are shown as /storage/sdcard0/dc for the bios and /storage/sdcard1/dc for the games. Should I change those? 
Hooby3dfx the version I have is actually the one on the Play Store.

**Comment by LoungeKatt** [comment]
No, that should be fine. Using the newest builds on a Shield tablet with 5.0.1 it appears to be working, so it could be something that was fixed along the way but isn't in the Play version yet.

**Comment by kaizen81** [comment]
I have installed all the OTA updates for the tablet so it should have the latest built. Is there another reicast apk (besides the one on the Play store)available that works with the Shield Tablet? Where can I find it? 
Thanks for all the help! I really want this to work..

**Comment by LoungeKatt** [comment]
http://builds.reicast.com are built whenever there are changes to the code. They are not as stable as the market build, but they have the newest code.

**Comment by kaizen81** [comment]
I downloaded the 3 latest builds from the link and tried them but I still get the same results. The bios works normally but when I select any game the emu crashes and returns to desktop. Is it certain that the Nvidia Shield tablet is supported?

**Comment by LoungeKatt** [comment]
![screenshot_2015-03-23-11-30-36](https://cloud.githubusercontent.com/assets/1173913/6783459/3ea505b4-d150-11e4-82c5-41946b04ce03.png)

"Using the newest builds on a Shield tablet with 5.0.1 it appears to be working" was referring to tests run on the physical hardware.

**Comment by kaizen81** [comment]
![screenshot_2015-03-23_18-12-33](https://cloud.githubusercontent.com/assets/11598299/6784479/a0392bce-d188-11e4-9e42-bf137b5737a3.png)

The built on my tablet is different

**Comment by LoungeKatt** [comment]
That looks like the one just before the one I'm using. They did publish an update they claimed resolved an issue with emulators, so it's possible you just need to update your tablet.

**Comment by kaizen81** [comment]
I see. I'm not rooted so I will to wait for the next OTA from Nvidia

**Comment by LoungeKatt** [comment]
It was an OTA from Nvidia. The one I posted a screen of is 2.2
http://shield.nvidia.com/support/shield-tablet/release-notes/1
There is a hotfix after that. If you haven't been notified of the update, you can always go into settings, about, and press check for updates.

**Comment by kaizen81** [comment]
I did check for updates as you said and it seems that my system is up to date. I'm pretty sure that I have already installed the 2.2 & 2.2.1 upgrades. I don't know why I get a different build from you. Is it possible that the OTA vary depending on the region of each user?

**Comment by hooby3dfx** [comment]
What games are you trying?

**Comment by kaizen81** [comment]
I have tried: Virtua Tennis 1&2, Cannon Spike, SNK vs Capcom 2, 3rd Strike, Power Stone 2, Dynamite Cop, DOA 2, Bangai-O.

I've seen some of the above run on devices with less graphical capabilities than the Shield Tablet.
Plus I tried other emus (ps1, n64, snes) and work just fine..

**Comment by hooby3dfx** [comment]
Do you know if those same backups are working on another device? Just
trying to rule out if the game files are causing the crash

**Comment by kaizen81** [comment]
No I haven't tried them on other devices

**Comment by LoungeKatt** [comment]
It is possible it's a different number if you have the LTE version. I would try the games on another device. DOA2 is one of the ones I used to test and had no issue.

**Comment by kaizen81** [comment]
No the tablet is the 16gig non LTE version. I'll try the games on a Note4 today..

**Comment by kaizen81** [comment]
Meanwhile I found other backups of the same games (from another source) and tried them. The result was the same. Probably it is not a matter of games

**Comment by kaizen81** [comment]
I tried DOA2 and Virtual Tennis 2 on a Note 3 and worked just fine.

**Comment by hooby3dfx** [comment]
can add a link to logs from after the crash? you can get that link right from the emulator.

**Comment by kaizen81** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1427819998071.txt

Is this the one? I was copied on the clipboard after I hit send logs

**Comment by hooby3dfx** [comment]
Is this from right after the crash?

**Comment by kaizen81** [comment]
Yes but I have to reopen the emu in order to get the file. I'm posting it again below

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1427828555148.txt

**Comment by skmp** [comment]
Can you try  http://reicast-builds.s3.amazonaws.com/builds/heads/master-c25ce04/reicast-android-debug-c25ce04.apk? Looks like dupplicate of #622

**Comment by skmp** [comment]
Try e2a70294d76de4b02750337e1dc684b8aa7c0100 http://reicast-builds.s3.amazonaws.com/builds/heads/feat/no-direct-memmap-e2a7029/reicast-android-debug-e2a7029.apk, It doesn't use the memory optimization

**Comment by kaizen81** [comment]
Still no luck. Does the same thing as all previous versions that I've tried...

**Comment by skmp** [comment]
Interesting. That's a different problem then (this build has been verified to fix the memory allocation issues). Thanks for reporting back.

**Comment by skmp** [comment]
Closing this as it is likely to be fixed. Re-open if not
